name 'php-httpd'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures php-httpd'
long_description 'Installs/Configures php-httpd'
version '0.1.0'
