name 'elastic'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures elastic'
long_description 'Installs/Configures elastic'
version '0.1.0'
